### ISSUE TITLE
Renaming Suggestion of Method Names to Make Them More Descriptive

### ISSUE THREAD

**Issue by AnonymousAccount4SE** [modalityone/modality#21]
### Renaming Suggestion of Method Names to Make Them More Descriptive
---
**Description**
---

We have developed a tool (**NameSpotter**) for identifying non-descriptive method names, and using this tool we find a non-descriptive method name in your repository:
```java
/* Non-descriptive Method Name in modality-ecommerce/modality-ecommerce-frontoffice-activities-payment/src/main/java/one/modality/ecommerce/frontoffice/activities/payment/PaymentActivity.java */

private static String digits(String s, int n, boolean right) {
        s = "" + s;
        while (s.length() < n)
            s = right ? s + '0' : '0' + s;
        return s.substring(s.length() - n);
    }
```

We considered "digits" as non-descriptive because it is too generic and lacks a verb indicating the action of this method. We proposed renaming the method name to "formatDigits". Consequently, when we look at this method name, we will be informed that it is a method written for formating the digits of numbers.

Do you agree with the judgment? 

- If not, could you please leave your valuable opinion?

- If you do agree, the relevant modification has been submitted as a PR, and thanks for your precious time to consider it.

**Comment by bjvickers** [comment]
Spam
